---
name: Molecule Test
'on':
  pull_request:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.8
    steps:
      - uses: actions/checkout@v2
        with:
          path: molecular-testing
          
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
          
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install molecule ansible-core
          python3 -m pip install --upgrade --user setuptools
          python3 -m pip install --user "molecule[docker]"
          molecule init role acme.my_new_role --driver-name docker
          #cd molecular-testing/roles/
          echo "  roles:" >> my_new_role/molecule/default/converge.yml
          echo "    - role: monitoring" >> my_new_role/molecule/default/converge.yml
      - name: Run script file
        run: |
         chmod +x molecular-testing/scripts/test.sh
         molecular-testing/scripts/test.sh
        shell: bash
      - name: Test with molecule
        run: cd my_new_role && molecule list && molecule create && molecule list && molecule converge
        

