---
name: Molecule Test
'on':
  pull_request:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          - 3.8
    steps:
      - uses: actions/checkout@v2
        with:
          path: molecular-testing
          
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
          
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install molecule ansible-core
          python3 -m pip install --upgrade --user setuptools
          python3 -m pip install --user "molecule[docker]"
          molecule init role acme.my_new_role --driver-name docker
          #ansible-galaxy init test-role
          #ansible-galaxy init molecule-test-role
          #cd molecular-testing/roles/
          #ln -s /molecular-testing/roles/ ./my_new_role/molecule/default/roles
          rm -rf my_new_role/molecule/default/molecule.yml
          $ vim my_new_role/molecule/default/molecule.yml
          echo "---" >> my_new_role/molecule/default/molecule.yml
          echo "dependency:" >> my_new_role/molecule/default/molecule.yml
          echo "  name: galaxy" >> my_new_role/molecule/default/molecule.yml
          echo "driver:" >> my_new_role/molecule/default/molecule.yml
          echo "  name: docker" >> my_new_role/molecule/default/molecule.yml
          echo "platforms:" >> my_new_role/molecule/default/molecule.yml
          echo "  - name: instance" >> my_new_role/molecule/default/molecule.yml
          echo "    image: quay.io/centos/centos:stream8" >> my_new_role/molecule/default/molecule.yml
          echo "    pre_build_image: true" >> my_new_role/molecule/default/molecule.yml
          echo "provisioner:" >> my_new_role/molecule/default/molecule.yml
          echo "  name: ansible" >> my_new_role/molecule/default/molecule.yml
          echo "  env:" >> my_new_role/molecule/default/molecule.yml
          echo "    ANSIBLE_ROLES_PATH: '../../roles'" >> my_new_role/molecule/default/molecule.yml
          echo "verifier:" >> my_new_role/molecule/default/molecule.yml
          echo "  name: ansible" >> my_new_role/molecule/default/molecule.yml
          echo "  roles:" >> my_new_role/molecule/default/converge.yml
          echo "    - role: monitoring" >> my_new_role/molecule/default/converge.yml
      - name: Test with molecule
        run: cd my_new_role && molecule list && molecule create && molecule list && molecule converge
        

